// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateHabitInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
}

type DeleteHabitInput struct {
	ID string `json:"id"`
}

type Habit struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	CreatedAt   string  `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateHabitInput struct {
	ID          string  `json:"id"`
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
}
